### ISSUE TITLE
Speeding the training on mixed data set - categorical data, numerical and text. 

### ISSUE THREAD

**Issue by vinay-k12** [worldbank/REaLTabFormer#26]
Trying to train the model on custom data which has various categorical feature with very high diversity like City, text features and numerical feature. Data size is small - 380K. 

But the training was never starting! It is stuck at this for few hours! 

<img width="1348" alt="image" src="https://github.com/worldbank/REaLTabFormer/assets/19322429/4a81c648-6316-4ef1-b458-56fbdffc7699">

How to improve the training?

**Comment by avsolatorio** [comment]
Hi @vinay-k12 , I think it's because of the cardinality of your data that makes the bootstrapping part not progress. What you could try is not to use the automated termination based on the bootstrap statistic; instead, you can use a validation sample.

Try:

```Python
# Use 20% of the data as a validation set early-stopping.
rtf_model = REaLTabFormer(
    model_type="tabular",
    gradient_accumulation_steps=4,
    logging_steps=100,
    train_size=0.8,
)

# Fit the model without sensitivity bootstrapping.
rtf_model.fit(df, n_critic=0)
```

This will fit the data directly. Hope this helps!
